#!/usr/bin/bash
# Script used to change the /etc/resolv.conf file automatically for differente usages 
# usage : chdns [MODE]
# MODE :
# crypt for encrypted dns with stubby and dnsmasq
# vpn for vpn access dns configuration
# std for standard dns configuration (quad9 and cloudfare) 
# mode print the current dns configuration

file_name=$(basename "$0")
dns_file_path="/etc" # default path of the resolv.conf file
dns_base_file="$dns_file_path/resolv.conf"
SUCCESS=0
ERROR=1

change_file () {
	if [ -z $1 ]
	then
		usage
		exit ERROR > /dev/null 2>&1
	else
		case $1 in
			crypt)
				change_mode 0 
			;;

			vpn)
				change_mode 2 
			;;

			std)
				change_mode 1
			;;
			*)
				get_mode
			;;
		esac
	fi
	exit $SUCCESS
					
}


change_mode () {
	echo "Verify if $dns_base_file is immutable..."
	attributes=$(lsattr "$dns_base_file")
	if ! [[ attributes == *"i"* ]] && [ "$1" -eq 0 ]
	then	
		echo "changing DNS configuration to encrypted mode..."
		sudo sh -c "echo -e \"nameserver ::1\nnameserver 127.0.0.1\noptions trust-ad\" > $dns_base_file" 
		sudo chattr +i $dns_base_file
		reload_configs 1
		echo "Done, enjoy encrypted DNS :)"

	elif ! [[ attributes == *"i"* ]] && [ "$1" -ne  0 ];then
		if [ "$1" -eq 1 ]
		then 
			echo "Changing DNS configuration to standard mode..."
			sudo sh -c "echo -e \"nameserver 9.9.9.9\nnameserver 1.1.1.1\" > $dns_base_file"
			sudo chattr +i $dns_base_file
			reload_configs 2
			echo "Done!"	

		else
			echo "Changing DNS configuration to VPN mode..."
			sudo sh -c "echo -e \" \n\" > $dns_base_file"
			reload_configs 2
		fi
	elif [[ attributes == *"i"* ]] && [ "$1" -ne  0 ];then
		echo "$dns_base_file has chattr +i set changing..."
		sudo chattr -i $dns_base_file
		if [ "$1" -eq 1 ]
		then 
			echo "Changing DNS configuration to standard mode..."
			sudo sh -c "echo -e \"nameserver 9.9.9.9\nnameserver 1.1.1.1\" > $dns_base_file"
			sudo chattr +i $dns_base_file
			reload_configs 2
			echo "Done!"	

		else
			echo "Changing DNS configuration to VPN mode..."
			sudo sh -c "echo -e \"\n\" > $dns_base_file" 
			reload_configs 2
		fi
	else
		echo "changing DNS configuration to encrypted mode..."
		sudo chattr -i $dns_base_file
		sudo sh -c "echo -e \"nameserver ::1\nnameserver 127.0.0.1\noptions trust-ad\" > $dns_base_file" 
		sudo chattr +i $dns_base_file
		reload_configs 1
		echo "Done, enjoy encrypted DNS :)"
	
	fi
	

}

#TODO

get_mode () {
	content=$(head -1 $dns_base_file)
	if [[ $content == "nameserver ::1" ]]
	then
		echo -e "Current DNS configuration mode => \e[32m ECRYPTED\e[0m"
	elif  [[ $content == "nameserver 9.9.9.9" ]];then
		echo -e "Current DNS configuration mode => \e[31m STANDARD / BASIC\e[0m"
	else
		echo -e "Current DNS configuration => \e[31m VPN / FREE\e[0m"
	fi
}


usage () {
	echo "usage : $file_name [MODE]"
	echo -e "MODE\n \
		crypt : for encrypted DNS configuration with stubby and dnsmasq\n \
		vpn   : for vp DNS configuration file\n \
		std   : for a standadr DNS configuration file\n \
		mode  : to display the current DNS configuration"
}

reload_configs () {

	echo "reloading configs..."
	case $1 in
		1)
			sudo systemctl restart NetworkManager \
			&& sudo systemctl restart stubby.service dnsmasq.service
		;;
		*)
			sudo systemctl stop --now stubby.service \
			&& sudo systemctl stop --now dnsmasq.service \
			&& sudo systemctl restart NetworkManager
		;;
	esac
}

change_file $1

